#!/usr/bin/env bash
# Generated by `configme install` — reproduces this install.
set -euo pipefail
# target=FastHydrology  machine=macbook  compiler=gfortran

# --- clone ---
git clone git@github.com:fesmc/FastHydrology.git /Users/alrobi001/tmp/FastHydrology
# fesm-utils: link to existing checkout at /Users/alrobi001/models/fesm-utils
ln -s /Users/alrobi001/models/fesm-utils /Users/alrobi001/tmp/FastHydrology/fesm-utils
# fesm-utils/utils: component of fesm-utils (not cloned)

# --- manifest ---
mkdir -p /Users/alrobi001/tmp/FastHydrology/.configme  # write .configme/manifest.toml

# --- links ---

# --- configure (per package) ---
# fesm-utils: linked external (no configure)
# fesm-utils/utils: linked external (no configure)
(cd /Users/alrobi001/tmp/FastHydrology && configme config FastHydrology -m macbook -c gfortran)
